"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import Turnstile from "react-turnstile";
import styles from "./Contact.module.css";
import { captureAttribution, type Attribution } from "@/lib/attribution";
import { trackEvent, trackLeadOnce } from "@/lib/analytics";

async function fileToDataUrl(file: File){const buffer=await file.arrayBuffer();return `data:${file.type};base64,${btoa(String.fromCharCode(...new Uint8Array(buffer)))}`}

export default function Contact({compact=false}:{compact?:boolean}){
  const [captchaToken,setCaptchaToken]=useState(""); const [loading,setLoading]=useState(false); const [sent,setSent]=useState(false); const [error,setError]=useState(""); const [tracking,setTracking]=useState<Attribution>({landingPage:"",referrer:""}); const [started,setStarted]=useState(false); const siteKey=process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY;
  useEffect(()=>setTracking(captureAttribution()),[]);
  function start(){if(!started){setStarted(true);trackEvent("start_quote_form",{form_name:"quote"})}}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const form=e.currentTarget,fd=new FormData(form);if(fd.get("website"))return;if(!fd.get("consent")){setError("Debes aceptar la política de privacidad.");return}if(siteKey&&!captchaToken){setError("Completa la verificación anti-bot.");return}const file=fd.get("attachment") as File;if(file?.name&&!['image/jpeg','image/png','application/pdf'].includes(file.type)){setError("La fotografía debe ser JPG, PNG o PDF.");return}if(file?.size>8*1024*1024){setError("El archivo no puede superar 8 MB.");return}setLoading(true);trackEvent("submit_quote_form",{form_name:"quote"});const width=String(fd.get("width")||"").trim(),height=String(fd.get("height")||"").trim();const message=[String(fd.get("message")||"").trim(),width||height?`Medidas aproximadas: ${width||"?"} ancho × ${height||"?"} alto`:""].filter(Boolean).join("\n\n");const body={tab:"empresa",name:fd.get("name"),company:fd.get("company"),email:fd.get("email"),phone:fd.get("phone"),city:fd.get("city"),eventType:fd.get("eventType"),subject:`Solicitud de presupuesto: ${fd.get("eventType")}`,message,captchaToken,attribution:tracking,page:location.href,attachment:file?.name?{name:file.name,type:file.type,size:file.size,dataUrl:await fileToDataUrl(file)}:undefined};try{const res=await fetch('/api/contact',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await res.json().catch(()=>({}));if(!res.ok)throw new Error(result.error||'No se pudo enviar la solicitud.');setSent(true);trackLeadOnce(result.leadId);form.reset();setCaptchaToken("")}catch(err){setError(err instanceof Error?err.message:'No se pudo enviar la solicitud.')}finally{setLoading(false)}}
  return <main id="solicitar-presupuesto" className={`container ${styles.contact} ${compact?styles.compact:""}`}><header className={styles.intro}><p>Presupuesto sin compromiso</p>{compact?<h2>Cuéntanos tu proyecto</h2>:<h1>Cuéntanos tu proyecto</h1>}<span>No necesitas conocer las especificaciones. Indica el espacio, el uso y unas medidas aproximadas; te ayudaremos a definir la solución.</span></header><div className={styles.contact__grid}><section className={`${styles.contact__panel} ${styles.contact__form}`}><form onSubmit={submit} onFocus={start}>
    <div className={styles.row}><Field label="Nombre *" name="name" required autoComplete="name"/><Field label="Empresa" name="company" autoComplete="organization"/></div>
    <div className={styles.row}><Field label="Email *" name="email" type="email" required autoComplete="email"/><Field label="Teléfono" name="phone" type="tel" autoComplete="tel"/></div>
    <div className={styles.row}><Field label="Ciudad" name="city" autoComplete="address-level2"/><label className={styles.field}>Tipo de solución *<select name="eventType" required defaultValue=""><option value="" disabled>Selecciona una opción</option>{["Pantalla LED interior","Pantalla LED exterior","Pantalla LED para escaparate","Digital signage","Videowall","Proyecto audiovisual","No lo sé / necesito asesoramiento"].map(x=><option key={x}>{x}</option>)}</select></label></div>
    <fieldset className={styles.measure}><legend>Medidas aproximadas (opcional)</legend><div className={styles.row}><Field label="Ancho" name="width" placeholder="Ej. 3 m"/><Field label="Alto" name="height" placeholder="Ej. 2 m"/></div></fieldset>
    <label className={styles.field}>Mensaje<textarea name="message" rows={5} placeholder="¿Dónde irá instalada y qué quieres comunicar?"/></label>
    <label className={styles.field}>Fotografía del espacio (opcional)<input type="file" name="attachment" accept="image/jpeg,image/png,application/pdf" onChange={e=>e.target.files?.[0]&&trackEvent("upload_project_photo",{file_type:e.target.files[0].type})}/><small>JPG, PNG o PDF. Máximo 8 MB.</small></label>
    {siteKey&&<Turnstile sitekey={siteKey} onVerify={setCaptchaToken} onExpire={()=>setCaptchaToken("")} theme="light" action="quote"/>}
    <label className={styles.checkbox}><input type="checkbox" name="consent" required/> Consiento el tratamiento de mis datos para responder a esta solicitud y he leído la <Link href="/privacidad" target="_blank">política de privacidad</Link>.</label>
    {error&&<p className={styles.error} role="alert">{error}</p>}{sent&&<p className={styles.success} role="status">Hemos recibido tu solicitud. Revisaremos las necesidades del proyecto y nos pondremos en contacto contigo.</p>}
    <button className={styles.btnCta} disabled={loading}>{loading?'Enviando…':'Solicitar presupuesto'}</button><input className={styles.hp} name="website" tabIndex={-1}/>
  </form></section><aside className={styles.sidebar}><h2>¿Qué nos ayuda a preparar la propuesta?</h2><ul><li>Una fotografía del espacio</li><li>Medidas aproximadas</li><li>Distancia de visualización</li><li>Uso interior o exterior</li><li>Tipo de contenido</li></ul><p>También puedes escribir a <a href="mailto:info@myl3d.es">info@myl3d.es</a> o usar WhatsApp.</p><a className={styles.whatsapp} href="https://wa.me/34692903572?text=Hola%2C%20estoy%20interesado%20en%20una%20soluci%C3%B3n%20de%20pantallas%20para%20mi%20empresa%20y%20me%20gustar%C3%ADa%20solicitar%20informaci%C3%B3n." target="_blank" rel="noreferrer">Abrir WhatsApp</a></aside></div></main>
}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const{label,...input}=props;return <label className={styles.field}>{label}<input {...input}/></label>}
