export type SeoSection = { title: string; text: string; items?: string[] };
export type SeoPage = {
  slug: string; title: string; description: string; eyebrow: string; intro: string;
  sections: SeoSection[]; uses: string[]; cta: string; ctaText: string;
  faqs: Array<{ question: string; answer: string }>;
};

export const seoPages: Record<string, SeoPage> = {
  "pantallas-led-escaparates": {
    slug: "pantallas-led-escaparates", title: "Pantallas LED para escaparates", eyebrow: "Visibilidad comercial",
    description: "Pantallas LED para escaparates: opciones, brillo, tamaño, pixel pitch, instalación y gestión. Envíanos una foto y medidas para solicitar presupuesto.",
    intro: "Haz visible tu comunicación desde la calle con una pantalla dimensionada para la luz, el espacio y la distancia real de lectura.",
    sections: [
      { title: "Qué solución puede encajar", text: "Una pantalla LED modular permite adaptar el formato al hueco disponible. Un monitor profesional de alta luminosidad puede ser adecuado cuando se busca un formato estándar. La elección depende del cristal, la exposición solar, el tamaño y la distancia de visualización.", items: ["Instalación interior detrás del cristal", "LED modular para formatos a medida", "Monitor profesional para formatos estándar"] },
      { title: "Brillo, tamaño y distancia", text: "No basta con elegir la pantalla más brillante. Orientación, luz directa, reflejos, horario y transparencia del cristal determinan la visibilidad. El tamaño se valora junto con la distancia desde la que se leerá el contenido." },
      { title: "Pixel pitch explicado de forma sencilla", text: "El pixel pitch es la distancia entre los puntos de luz. Influye en la definición percibida, especialmente cuando el público está cerca. No necesitas elegirlo: se define después de estudiar la distancia y el tipo de contenido." },
      { title: "Instalación y operación", text: "La propuesta debe contemplar soporte o estructura, alimentación, acceso para mantenimiento y ventilación. También conviene valorar el consumo, las horas de funcionamiento, la creación de contenidos y la gestión remota." },
    ], uses: ["Inmobiliarias", "Concesionarios", "Gimnasios", "Retail", "Restaurantes", "Agencias"],
    cta: "Envíanos una foto y las medidas aproximadas", ctaText: "No necesitas conocer las especificaciones técnicas. Cuéntanos dónde quieres instalarla y te ayudamos a definir la solución.",
    faqs: [{question:"¿LED modular o monitor profesional?",answer:"Depende del formato, la distancia de visión, la luminosidad y las condiciones del escaparate. Estudiamos ambas opciones cuando sean viables."},{question:"¿Puedo gestionar el contenido a distancia?",answer:"La gestión remota puede incluirse en el planteamiento para actualizar campañas y horarios sin acceder físicamente a la pantalla."}]
  },
  "precio-pantalla-led": {
    slug:"precio-pantalla-led", title:"¿Cuánto cuesta una pantalla LED?", eyebrow:"Presupuesto a medida", description:"Conoce qué determina el precio de una pantalla LED: dimensiones, pixel pitch, uso interior o exterior, estructura, montaje y soporte.",
    intro:"El precio se calcula según el espacio y la aplicación. Sin dimensiones ni condiciones de instalación, una cifra por metro cuadrado puede resultar engañosa.",
    sections:[{title:"Equipo y superficie",text:"El tamaño total, la superficie, el pixel pitch, el brillo y la electrónica condicionan el equipo. El uso interior o exterior añade requisitos distintos de protección y visibilidad."},{title:"Instalación y puesta en marcha",text:"La estructura, el acceso, el montaje, el transporte, la instalación eléctrica y la configuración forman parte del alcance que debe definirse."},{title:"Operación y soporte",text:"El presupuesto puede considerar control de contenidos, formación, mantenimiento y soporte. Deben compararse alcances equivalentes, no solo el coste del panel.",items:["Dimensiones y ubicación", "Distancia de visualización", "Condiciones de luz", "Acceso y estructura", "Gestión de contenidos"]}], uses:["Interior","Exterior","Escaparates","Espacios corporativos"], cta:"Solicitar estimación",ctaText:"Solicita una estimación según dimensiones y aplicación. No publicamos cifras sin una base técnica verificable.",faqs:[{question:"¿Existe un precio fijo por m²?",answer:"No hay un único precio representativo: la tecnología, la protección, la electrónica y la instalación cambian el alcance."},{question:"¿Qué información necesito enviar?",answer:"Una foto, medidas aproximadas, ubicación, uso interior o exterior y distancia habitual de visualización permiten preparar una primera estimación."}]
  },
  "pantallas-led-interior": {
    slug:"pantallas-led-interior",title:"Pantallas LED para interior",eyebrow:"Espacios interiores",description:"Pantallas LED para interior en retail, empresas, showrooms, gimnasios, restaurantes y salas. Configuración según espacio y distancia.",intro:"Soluciones de gran formato para comunicar, presentar información o crear un punto visual, dimensionadas para el espacio y la proximidad del público.",sections:[{title:"Dónde se utilizan",text:"En salas, retail, empresas, showrooms, gimnasios, restaurantes y eventos internos. El objetivo y el contenido ayudan a decidir formato y ubicación."},{title:"Distancia, brillo y definición",text:"En interior suele priorizarse la comodidad visual y la definición a corta distancia. El pixel pitch se selecciona según la distancia habitual; el brillo se ajusta al entorno, no al máximo disponible."},{title:"LED frente a otras tecnologías",text:"El LED modular facilita grandes superficies y formatos personalizados. Para tamaños estándar y distancias muy cortas, un monitor profesional o videowall puede ser más adecuado. La comparación debe hacerse según cada aplicación."},{title:"Del espacio a la instalación",text:"Se revisan medidas, soporte, alimentación, ventilación, acceso para mantenimiento y sistema de contenidos antes de concretar la propuesta."}],uses:["Salas y auditorios","Retail y showrooms","Empresas","Gimnasios","Restaurantes","Eventos internos"],cta:"Solicitar presupuesto",ctaText:"Envíanos una foto, medidas aproximadas y cuéntanos desde qué distancia se verá.",faqs:[{question:"¿Necesito saber el pixel pitch?",answer:"No. Con la distancia de visualización y el tipo de contenido podemos estudiar el rango adecuado."},{question:"¿Se puede actualizar el contenido en remoto?",answer:"Sí, puede plantearse un sistema de gestión remota según el número de pantallas y ubicaciones."}]
  },
  "pantallas-led-exterior": {
    slug:"pantallas-led-exterior",title:"Pantallas LED para exterior",eyebrow:"Comunicación exterior",description:"Pantallas LED para exterior: visibilidad, protección, estructura, mantenimiento y seguridad según ubicación y proyecto.",intro:"Una instalación exterior debe estudiarse como un conjunto: pantalla, estructura, entorno, acceso, alimentación, mantenimiento y condiciones de visualización.",sections:[{title:"Visibilidad en el entorno",text:"La luminosidad necesaria depende de la orientación, la incidencia solar, el horario y la distancia. Tamaño, altura y pixel pitch se evalúan según el punto real de observación."},{title:"Protección y condiciones ambientales",text:"El equipo y sus conexiones deben ser adecuados para las condiciones previstas. La lluvia, polvo, temperatura, viento y exposición continuada se consideran al seleccionar y diseñar la solución."},{title:"Estructura, instalación y seguridad",text:"El soporte, las cargas, el acceso, la alimentación y el montaje deben ser definidos por profesionales competentes para el proyecto. El acceso frontal o trasero condiciona el mantenimiento."},{title:"Normativa y permisos",text:"La normativa y los permisos pueden variar según el municipio, la ubicación y las características del proyecto. Deben verificarse con la administración y los técnicos correspondientes antes de ejecutar la instalación."}],uses:["Fachadas comerciales","Recintos","Accesos","Comunicación corporativa"],cta:"Solicitar presupuesto",ctaText:"Cuéntanos la ubicación y envíanos fotografías y medidas aproximadas para estudiar el proyecto.",faqs:[{question:"¿Siempre necesito un permiso?",answer:"No puede afirmarse de forma general. Depende del municipio, la ubicación y el proyecto; conviene verificarlo antes de instalar."},{question:"¿Cómo se planifica el mantenimiento?",answer:"Se define el acceso seguro a módulos, conexiones y electrónica desde la fase de diseño."}]
  },
  "digital-signage": {
    slug:"digital-signage",title:"Digital Signage para empresas",eyebrow:"Cartelería digital",description:"Digital signage para empresas: pantallas, player, software, contenidos, programación y gestión remota para una o varias ubicaciones.",intro:"Organiza y actualiza la comunicación en pantallas desde un sistema pensado para el contenido, los horarios y las ubicaciones de tu empresa.",sections:[{title:"Qué compone un sistema",text:"Un proyecto combina una o varias pantallas, un player cuando sea necesario, software de gestión y contenidos preparados para cada formato."},{title:"Programación y gestión remota",text:"La plataforma puede organizar parrillas por horario, campaña o ubicación. En despliegues con varias sedes, la gestión central ayuda a mantener coherencia y adaptar mensajes localmente."},{title:"Diseño para la operación diaria",text:"Antes de elegir hardware conviene definir quién publica, con qué frecuencia, qué ocurre si se pierde la conexión y cómo se supervisa el estado de los equipos."},{title:"Cómo preparar una propuesta",text:"Indica número de ubicaciones y pantallas, tipo de contenido, frecuencia de actualización y responsables internos. Con esa información se puede definir una arquitectura proporcionada."}],uses:["Retail","Hoteles","Gimnasios","Restaurantes","Inmobiliarias","Oficinas"],cta:"Cuéntanos qué necesitas",ctaText:"Descríbenos las ubicaciones, pantallas y contenidos que quieres gestionar y prepararemos una propuesta.",faqs:[{question:"¿Qué es un player?",answer:"Es el equipo que reproduce el contenido y conecta la pantalla con el sistema de gestión cuando la arquitectura lo requiere."},{question:"¿Puedo gestionar varias sedes?",answer:"Sí. La configuración puede centralizar contenidos y programaciones para distintas ubicaciones."}]
  }
};

export const seoSlugs = Object.keys(seoPages);
